 $(document).ready(function(){
    $("#ab").click(function(){
        $("#abreg").show();
        $("#aj").hide();
        $("#in").hide();
        $("#db").hide();
        $("#btn").hide();
     });
    $("#X").click(function(){
		$("#abreg").hide();
        $("#aj").show();
        $("#in").show();
        $("#db").show();
        $("#btn").show();
	});
     $("#in").click(function(){
        $("#abreg1").show();
        $("#ab").hide();
        $("#aj").hide();
        $("#db").hide();
        $("#btn").hide();
     });
    $("#X1").click(function(){
		$("#abreg1").hide();
        $("#ab").show();
        $("#aj").show();
        $("#db").show();
		$("#btn").show();
	});
    $("#db").click(function(){
        $("#abreg2").show();
        $("#ab").hide();
        $("#aj").hide();
        $("#in").hide();
        $("#btn").hide();
     });
    $("#X2").click(function(){
		$("#abreg2").hide();
        $("#ab").show();
        $("#aj").show();
        $("#in").show();
		$("#btn").show();
	});
	$("#button").click(function(){
        $("#abreg").show();
	});
	$("#btn").click(function(){
		$("#abreg3").show();
		$("#btn").hide();
		$("#ab").hide();
		$("#aj").hide();
        $("#in").hide();
        $("#db").hide();
	});
	$("#X3").click(function(){
		$("#abreg3").hide();
		$("#btn").show();
		$("#ab").show();
		$("#aj").show();
        $("#in").show();
        $("#db").show();
	});
	$("#old").click(function() {
        $('#old').val("12345");
	});
 });

 

